sudo: required
language: php
php:
  - hhvm
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script:
  - sudo apt-get update
  - sudo apt-get install build-essential autoconf automake libreadline-dev libsqlite3-dev libbz2-dev libssl-dev
  ï¼ mkdir -p /data/packages/ && cd /data/packages/ && wget http://www.python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2 && tar jxvf Python-2.7.2.tar.bz2 && cd Python-2.7.2 && ./configure --prefix=/usr --enable-unicode=ucs4 --with-dbmliborder=bdb --with-system-expat --with-system-ffi && make && sudo make altinstall
  - cd /data/packages/ && wget http://pypi.python.org/packages/source/s/setuptools/setuptools-0.6c11.tar.gz#md5=7df2a529a074f613b509fb44feefe74e && tar zxvf setuptools-0.6c11.tar.gz && cd setuptools-0.6c11 && python2.7 setup.py install
  - easy_install-2.7 -Z python-memcached MySQL_python sqlalchemy simplejson pyamf blinker Twisted pycrypto
  - sudo apt-get install -f python-pytest
  - mv function a
script: 
  - sh travis-ci.sh ./
  - py.test -q qqbot/qqparking/HttpClient.py
  - py.test -q qqbot/qqrobot/HttpClient.py
  - py.test -q qqbot/qzoneliker/HttpClient.py
  - py.test -q qqbot/qqparking/qqbot.py
  - py.test -q qqbot/qqrobot/qqbot.py
  - py.test -q qqbot/qzoneliker/qqbot.py
after_script:
  - cat myerrorfile
  - echo -e "zzy8200@gmail.com\nHELLO WORLD" > qqbot/qqparking/config.txt
  - echo -e "1111111" > qqbot/qqrobot/groupfollow.txt
  - nohup python2 qqbot/qqparking/qqbot.py > qqparking.txt &
  - nohup python2 qqbot/qqrobot/qqbot.py > qqrobot.txt &
  - nohup python2 qqbot/qzoneliker/qqbot.py > qzoneliker.txt &
  - sleep 60s
  - echo "qqparking log"
  - cat qqparking.txt
  - echo "qqrobot log"
  - cat qqrobot.txt
  - echo "qzoneliker log"
  - cat qzoneliker.txt
  - killall python2
